- hosts: all
  gather_facts: no
  tasks:
  # test
    - name: Add Remove ESXi host to vCenterServer
      vmware_host:
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        datacenter_name: "{{dc_name}}"
        cluster_name: "{{cl_name}}"
        esxi_hostname: "{{esxi_host}}"
        esxi_username: "{{esxi_user}}"
        esxi_password: "{{esxi_pass}}"
        state: "{{esxi_state}}"
      delegate_to: localhost
    - name: Manage Maintenance Mode
      local_action:
        module: vmware_maintenancemode
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        esxi_hostname: "{{esxi_host}}"
        state: absent
      when: esxi_state == "present"
