- hosts: 127.0.0.1
  tasks:
  - name: Boot up instance
    vmware_guest:
      hostname: "{{hostname}}"
      username: "{{user_name}}"
      password: "{{password}}"
      datacenter: DC
      cluster: CL
      name: "{{vmname}}{{item}}"
      template: "{{template}}"
      networks:
      - name: VM Network
        ip: 192.168.1.{{item}}
        netmask: <subnet>
        gateway: <gateway ip>
        dns_servers:
        - <dns ip>
      state: poweredon
      disk:
      - datastore: NFS
        size_gb: 15
        type: thin
      validate_certs: no
    with_sequence: count={{number}}
