- hosts: all
  tasks:
    - name: Standard Switch Config
      action:
        module: vmware_vswitch
        hostname: "{{esxi_host}}"
        username: "{{esxi_user}}"
        password: "{{esxi_password}}"
        validate_certs: False
        switch: "{{vss_name}}"
        nics: "{{vmnic_name}}"
        mtu: "{{mtu}}"
        state: "{{vss_state}}"
      delegate_to: localhost
